### ISSUE TITLE
docker starting failure

### ISSUE THREAD

**Issue by d4rkd3n1337** [naim94a/lumen#116]
**Describe the bug**
Hey Naim! At first I wanted to run lumen without a doker, but I didn't understand where schema.sql is located. but I managed to build the lumen and connect the ida to it. when trying to send the idb received an error
```
lumen: database error; please try again later..
Failed to execute the "LuminaViewAllMds" command
```
and on server
`failed to extract, db: the "funcs" relation does not exist.`
  So I had to resort to docker. But even here I was in for a setback. I used the default docker-compose file. At startup, compilation started, but ended with an error too. 

`root@lumen-srv:/lumen# docker-compose up
Building lumina
Sending build context to Docker daemon  452.6kB
Step 1/22 : FROM rust:1.68.2-slim-buster
 ---> 352f3bc068fa
Step 2/22 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 95e5c1cdf4c0
Step 3/22 : RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests ca-certificates pkg-config libssl-dev libpq-dev
 ---> Using cache
 ---> ad80587b6d79
Step 4/22 : ENV CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
 ---> Using cache
 ---> a8ae4f5cf938
Step 5/22 : RUN --mount=type=cache,target=$CARGO_HOME/registry  cargo install diesel_cli --version 2.0.1 --no-default-features --features postgres
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
ERROR: Service 'lumina' failed to build : Build failed`

**To Reproduce**
docker-compose up -d

**Server (please complete the following information):**
 - OS: Debian 12 bookworm
 - Architecture: x86_64
 - Docker: 20.10.24+dfsg1, build 297e128
 - docker-copose: 1.29.2, build unknown
 
**Client (please complete the following information):**
 - OS: Windows 11
 - Architecture: x86_64
 - IDA Version: 7.7.220118

**Comment by naim94a** [comment]
After searching a bit online, it is my understanding that BuildKit is enabled by default on `docker compose` (v2+), but can be enabled in your environment's `docker-daemon.json` or by setting environment variables (see the link in the error).
