### ISSUE TITLE
Can't connect on 8.3.230608

### ISSUE THREAD

**Issue by gir489returns** [naim94a/lumen#117]
**Describe the bug**
I tried to replicate the steps on https://abda.nl/lumen/#ida--80 under Windows as best as possible, however, I can't get IDA to connect to the server.

**To Reproduce**
Download [socat for windows](https://github.com/valorisa/socat-1.7.4.4_for_Windows) and place the hexrays.crt into the same folder and run it with command given on the website.
Create a BAT file that does the same thing the instructions say but uses SET instead of export and runs ida64.exe after.
Have IDA try to connect to the Lumen server via localhost port 1234.
Bug appears.

**Expected behavior**
Should connect to the Lumen server.

**Server (please complete the following information):**
Whatever abda.nl is running.

**Client (please complete the following information):**
 - OS: Windows 11 22H2
 - Architecture: x64
 - IDA Version: 8.3.230608

**Additional context**
Here are the errors socat and IDA generate:

```
lumina: recv: An existing connection was forcibly closed by the remote host.
2023/11/27 20:01:21 socat[41484] E SSL_connect(): error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
2023/11/27 20:01:21 socat[41484] E no peer certificate
2023/11/27 20:02:10 socat[32636] E SSL_connect(): error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
2023/11/27 20:02:10 socat[32636] E no peer certificate
2023/11/27 20:11:11 socat[32164] E SSL_connect(): error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
2023/11/27 20:11:11 socat[32164] E no peer certificate
2023/11/27 20:11:21 socat[28128] E SSL_connect(): error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
2023/11/27 20:11:21 socat[28128] E no peer certificate
```

**Comment by greenozon** [comment]
Similar issue

```
C:\Tmp\123>socat -s -dd tcp4-listen:1234,fork,reuseaddr openssl:lumen.abda.nl:1235,cafile=hexrays.crt
2023/12/03 21:06:34 socat[1954] N listening on AF=2 0.0.0.0:1234

```
in Ida83  got this

```
lumina: recv: An existing connection was forcibly closed by the remote host.
Command "LuminaViewAllMds" failed
lumina: recv: An existing connection was forcibly closed by the remote host.
Command "LuminaPullAllMds" failed
```

**Comment by lguilhermee** [comment]
Solution: 

`"socat -s -dd tcp4-listen:1234,fork,reuseaddr openssl:http://lumen.abda.nl:1235,verify=0,cafile=hexrays.crt"`

**Comment by greenozon** [comment]
what are the correct settings in the GUI?
those lead to error as well:

![image](https://github.com/naim94a/lumen/assets/765343/bcfc1b08-d162-4d85-952c-13d6d49d025b)

![image](https://github.com/naim94a/lumen/assets/765343/f0ad5b62-67f6-4057-8164-03f247a82f28)

**Comment by KillStr3aK** [comment]
> **Describe the bug** I tried to replicate the steps on https://abda.nl/lumen/#ida--80 under Windows as best as possible, however, I can't get IDA to connect to the server.
> 
> **To Reproduce** Download [socat for windows](https://github.com/valorisa/socat-1.7.4.4_for_Windows) and place the hexrays.crt into the same folder and run it with command given on the website. Create a BAT file that does the same thing the instructions say but uses SET instead of export and runs ida64.exe after. Have IDA try to connect to the Lumen server via localhost port 1234. Bug appears.
> 
> **Expected behavior** Should connect to the Lumen server.
> 
> **Server (please complete the following information):** Whatever abda.nl is running.
> 
> **Client (please complete the following information):**
> 
> * OS: Windows 11 22H2
> * Architecture: x64
> * IDA Version: 8.3.230608
> 
> **Additional context** Here are the errors socat and IDA generate:
> 
> ```
> lumina: recv: An existing connection was forcibly closed by the remote host.
> 2023/11/27 20:01:21 socat[41484] E SSL_connect(): error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
> 2023/11/27 20:01:21 socat[41484] E no peer certificate
> 2023/11/27 20:02:10 socat[32636] E SSL_connect(): error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
> 2023/11/27 20:02:10 socat[32636] E no peer certificate
> 2023/11/27 20:11:11 socat[32164] E SSL_connect(): error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
> 2023/11/27 20:11:11 socat[32164] E no peer certificate
> 2023/11/27 20:11:21 socat[28128] E SSL_connect(): error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
> 2023/11/27 20:11:21 socat[28128] E no peer certificate
> ```

the port is 1235

**Comment by lguilhermee** [comment]
> what are the correct settings in the GUI? those lead to error as well:
> 
> ![image](https://private-user-images.githubusercontent.com/765343/288332587-bcfc1b08-d162-4d85-952c-13d6d49d025b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4OTE4NjQsIm5iZiI6MTcwMTg5MTU2NCwicGF0aCI6Ii83NjUzNDMvMjg4MzMyNTg3LWJjZmMxYjA4LWQxNjItNGQ4NS05NTJjLTEzZDZkNDlkMDI1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxOTM5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGMwOWUwYWI3ZDliMzJmOTQ2Y2Q5NjViNjFiZTU5MzA1ZGM5OTdjZjE0NzMwYzNiMTFiNTJhNzQyNjk0YTEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hyzw64sUgDE6EZECmHDe5ppw7BuTeKCX82TUxCJ8hF8)
> 
> ![image](https://private-user-images.githubusercontent.com/765343/288332644-f0ad5b62-67f6-4057-8164-03f247a82f28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4OTE4NjQsIm5iZiI6MTcwMTg5MTU2NCwicGF0aCI6Ii83NjUzNDMvMjg4MzMyNjQ0LWYwYWQ1YjYyLTY3ZjYtNDA1Ny04MTY0LTAzZjI0N2E4MmYyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxOTM5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzllOTRjNjU4MTA4MzZkMjRiZDM0ZDhhZjhiMGVkOGFmNzVjZjkyYmQxMDhlNTQ2YjljMWMyY2I5NjYxZGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L1uyHHtjFBmXUCQYBFun1eHMmMToR4sOnjhbpjZJl8w)

This in incorrect. You need to redirect it to localhost if you are using socat.
Ip: either 127.0.0.1 or localhost, port should be: 1234
the username/password is: guest

you also had to put on enviroments variable LUMINA_TLS = 'FALSE' (windows case)

don't forgot to put the cert also in the same folder of socat

**Comment by gir489returns** [comment]
> Solution:
> 
> `"socat -s -dd tcp4-listen:1234,fork,reuseaddr openssl:http://lumen.abda.nl:1235,verify=0,cafile=hexrays.crt"`

I get the same error I posted in OP, setting LUMINA_TLS to FALSE has no effect. Connecting to localhost port 1234.

![image](https://github.com/naim94a/lumen/assets/100792176/47e4c684-bfae-4d18-a79a-bf4b8487ca6f)
![image](https://github.com/naim94a/lumen/assets/100792176/fdd28ba4-8636-49c5-afdf-b3d26b035b9c)
![image](https://github.com/naim94a/lumen/assets/100792176/c84b6419-66bf-4401-a9e1-469c942d1728)

**Comment by tomrus88** [comment]
You can try this little plugin I made. Just place those dll's into your IDA's plugins folder and try to connect to lumen.abda.nl port 1235 by configuring it in IDA settings. No need for LUMINA_TLS, socat or anything, only this plugin.
[luminafix.zip](https://github.com/naim94a/lumen/files/13691917/luminafix.zip)

**Comment by Pazaz** [comment]
> You can try this little plugin I made. Just place those dll's into your IDA's plugins folder and try to connect to lumen.abda.nl port 1235 by configuring it in IDA settings. No need for LUMINA_TLS, socat or anything, only this plugin. [luminafix.zip](https://github.com/naim94a/lumen/files/13691917/luminafix.zip)

Thanks Tom, this worked perfectly to connect to Lumen's public server and my own instance. Nice work.

**Comment by gir489returns** [comment]
> You can try this little plugin I made. Just place those dll's into your IDA's plugins folder and try to connect to lumen.abda.nl port 1235 by configuring it in IDA settings. No need for LUMINA_TLS, socat or anything, only this plugin. [luminafix.zip](https://github.com/naim94a/lumen/files/13691917/luminafix.zip)

Thanks for the plugin, but I still seem to be getting the same error.

```
Lumina Fix: init
Lumina Fix: IDA version 8.3.23.608 detected
Lumina Fix: initialized
lumina: recv: An existing connection was forcibly closed by the remote host.
Command "LuminaPullAllMds" failed
```

![image](https://github.com/naim94a/lumen/assets/100792176/519b8cc7-56c7-4768-8950-da92394e2de7)

**Comment by tomrus88** [comment]
> EDIT: It worked once, now it's back to doing the same thing. I found that running IDA as Administrator fixed the issue.
This is interesting, I haven't tried running without admin. May be patch fails to apply without admin rights.

**Comment by gir489returns** [comment]
> > EDIT: It worked once, now it's back to doing the same thing. I found that running IDA as Administrator fixed the issue.
> 
> This is interesting, I haven't tried running without admin. May be patch fails to apply without admin rights. Edit: tested it and it works fine with and without admin rights on my end

I have a feeling it has something to do the network not allowing IDA to contact the server without admin rights. Not sure, I just run bone stock Windows 11 23H2 machine for it with Windows Defender. When I reinstalled with the new key, it asked if I wanted to allow "The Interactive Disassembler" through the firewall, which I said yes to, but when I restarted the app, it got that forcibly closed by the remote host error again.

Not really sure what the rhyme or reason for requiring it to run as admin is, but I just know it fixed my issue and that's all I really care about. Funny enough, I didn't know who you were at first, you know, random guy posting a DLL kinda sus, but then I reversed it, and it looked good, and then I realized, you're the same guy behind the IDA keygen.

**Comment by b1scoito** [comment]
> You can try this little plugin I made. Just place those dll's into your IDA's plugins folder and try to connect to lumen.abda.nl port 1235 by configuring it in IDA settings. No need for LUMINA_TLS, socat or anything, only this plugin. [luminafix.zip](https://github.com/naim94a/lumen/files/13691917/luminafix.zip)

@naim94a Can we update the readme page with the contribution @tomrus88 made with this plugin?

**Comment by naim94a** [comment]
Once the plugin is open source, I would gladly reference it or integrate it into this repo

**Comment by tomrus88** [comment]
@gir489returns Can you try this updated version of plugin (i've added some additional messages for failure cases), so may be it will tell us where exactly it fails (if it fails) when you run IDA without admin rights? I'm still not sure if its a problem with plugin or something on your end...

[luminafix.zip](https://github.com/naim94a/lumen/files/13740333/luminafix.zip)

@b1scoito I don't have plans to open-source it at this time, but plugin is super simple, all it does is pattern search and replace of few bytes in memory. More specifically it patches TLS certificate validation function to always succeed. You can easily patch those bytes in ida.dll/ida64.dll manually on disk with hex editor and don't use plugin at all.

**Comment by Hazuki-san** [comment]
luminafix works for me @tomrus88

**Comment by tomrus88** [comment]
Also you can try with this build of socat, i've compiled it myself and tested connection using it and it worked fine for me.
How to use: unpack all files from this achieve, start run.cmd file, in IDA set lumina server to localhost and port 12345.
[socat-1.8.0.0.zip](https://github.com/naim94a/lumen/files/13783206/socat-1.8.0.0.zip)

**Comment by gir489returns** [comment]
> @gir489returns Can you try this updated version of plugin (i've added some additional messages for failure cases), so may be it will tell us where exactly it fails (if it fails) when you run IDA without admin rights? I'm still not sure if its a problem with plugin or something on your end...

The new plugin works now without IDA being in admin mode.

**Comment by p0358** [comment]
> I don't have plans to open-source it at this time, but plugin is super simple, all it does is pattern search and replace of few bytes in memory.

Why not? It is pretty simple indeed and someone could reproduce it, but why duplicate the effort?

**Comment by greenozon** [comment]
Does the lumina_fix plugin work for IDA8.4 Free/Demo?

**Comment by tomrus88** [comment]
> Does the lumina_fix plugin work for IDA8.4 Free/Demo?

Pretty sure IDA Free/Demo doesn't have Lumina support at all?

**Comment by ThisIsMyAltAccount** [comment]
@tomrus88 

There is DLL that lets you PULL (from Lumen servers only) with IDA Freeware 7.6 and older. Newer versions of IDA crash.

https://github.com/SohaibJundi/LemonIDA
![ida_free_lumina](https://github.com/naim94a/lumen/assets/76416336/0e685f34-2f7e-4d60-b968-029374c2e207)

My config for reference:
```
LUMINA_HOST = "192.168.254.30";
LUMINA_PORT = 1234
LUMINA_TLS = NO
```

**Comment by tomrus88** [comment]
> There is DLL that lets you PULL (from Lumen servers only) with IDA Freeware 7.6 and older. Newer versions of IDA crash.

Cool. I've created my own plugin that works with IDA Freeware 7.6-8.4 and also let you **push** to lumina server. You can try it by grabbing a copy below. Currently it's hardcoded to use lumen.abda.nl server. May be I'll add config that allows to specify different Lumina server someway, no promises...

[luminafree64.zip](https://github.com/naim94a/lumen/files/14473053/luminafree64.zip)

**Comment by greenozon** [comment]
THanks!
what are the steps to use it in IDA84 free?

I put into plugins/ dir and tried some sample app

questions
1) there is no Lumina menu 
2) options are kind of cut down for Lumina (if comparing with full 83
![image](https://github.com/naim94a/lumen/assets/765343/e99b5bbd-1b1d-4ca7-bab7-01df8905b5cb)

3) when I tried to do decompilation I hit this kind of (new) issue:

![image](https://github.com/naim94a/lumen/assets/765343/dc9e253d-f32d-44c9-87d6-49a8dc644169)

![image](https://github.com/naim94a/lumen/assets/765343/45fa1166-4909-4606-ad6b-6d31c8f1bb36)

**Comment by tomrus88** [comment]
There's context menu entries for pull/push and also same entries in Edit->LuminaFree menu. Also I forgot that IDA Freeware uses same server for it's cloud Decompiler, so decompiler won't work with plugin, may be there's some workaround exist, I don't know...

**Comment by greenozon** [comment]
In what specific context menu should I find the push/pull for Lumina? I cant fine it
also Idid not see Edit -> Lumina menu 

oh, I see - smth is wrong here.... 
any ideas?

LoadLibrary(C:\Progs\DA84Fre\plugins\luminafree64.dll) error: Unknown error, code: 0xC000001D
C:\Progs\DA84Fre\plugins\luminafree64.dll: can't load file

**Comment by tomrus88** [comment]
Is your CPU very old or something?

**Comment by greenozon** [comment]
Intel COre i7 is very old or...?

**Comment by greenozon** [comment]
dont say you have used ZMM + AVX512 :) 
those I definitely not haveing... sorry
could you please recompile to some common ground? eg SSE4 max

**Comment by tomrus88** [comment]
Try this version, may be it's more compatible with your CPU, i'm not sure. I've also changed Lumina to use secondary connection (this is only possible for IDA 8.3/8.4, older versions don't have this feature) so it's should be possible to use both Decompiler on primary connection and Lumina on secondary connection at same time.

[luminafree64.zip](https://github.com/naim94a/lumen/files/14473552/luminafree64.zip)

**Comment by greenozon** [comment]
hurrey!!!!!!!!!  the last one did the magic!  thx!

![image](https://github.com/naim94a/lumen/assets/765343/649bfdce-66cd-47e6-8c3c-187eae7e45af)

![image](https://github.com/naim94a/lumen/assets/765343/454b3728-48c5-4634-b260-f1419ba233e3)


kudos!

great present for latest & greatest bits :)

PS this is what I've seen in bootstrap in ida console:

![image](https://github.com/naim94a/lumen/assets/765343/54aed467-39a0-41d3-9fd5-46ef4cdec349)

**Comment by RaceIsIm** [comment]
Tysm

**Comment by tomrus88** [comment]
@b1scoito @p0358  @naim94a 

Last night I've created new open source version of the plugin, which uses different method of fixing TLS certificate validation, but there's a catch: it is required to generate new compatible certificate that uses certificate chain like official ones for plugin to work correctly. I've tested it by connecting to local instance of official private lumina server, but it should work with unofficial Lumen server too (may be it need different format of certificates, haven't checked this yet). More info here: https://github.com/naim94a/lumen/issues/124#issuecomment-1998793313

**Comment by greenozon** [comment]
@tomrus88   looks like there is  a bug
when for some reason lumen server is off,  eg:

```
The initial autoanalysis has been finished.
lumina: connection closed (send: An existing connection was forcibly closed by the remote host.). Trying to reconnect...
lumina: applied metadata to 693 functions.
```

**Comment by tomrus88** [comment]
> @tomrus88 looks like there is a bug thats on ida 83 + your last plugin when for some reason lumen server is off, eg:
> 
> ```
> The initial autoanalysis has been finished.
> lumina: connection closed (send: An existing connection was forcibly closed by the remote host.). Trying to reconnect...
> lumina: applied metadata to 693 functions.
> ```

What bug? It says metadata applied, so what's wrong?

**Comment by greenozon** [comment]
agree, it's not obvious from the message above
what has happened is as follows:

tried to use lumina to apply sigs to my db
it started to dump it out
but then all of a sudden it stopped and in the end I saw 0 updates from lumina server
but the log says 693 functions were applied (NOT in reality)

hope it clarifies the flow

**Comment by tomrus88** [comment]
This has nothing to do with plugin anyway, since plugin doesn't do any work by itself. Also not sure which plugin you talking about, since I posted multiple ones and they do different things... One is just a patch to disable certificate check, and another one does a bit more than that...

**Comment by tomrus88** [comment]
> > Try this version, may be it's more compatible with your CPU, i'm not sure. I've also changed Lumina to use secondary connection (this is only possible for IDA Freeware 8.3/8.4, older versions don't have this feature) so it's should be possible to use both cloud Decompiler on primary connection and Lumina on secondary connection at same time.
> > [luminafree64.zip](https://github.com/naim94a/lumen/files/14480346/luminafree64.zip)
> 
> Hi @tomrus88 ,
> 
> This looks quite interesting. Do you think there is any chance for a Linux (amd64) build?

I do have Linux/MacOS builds (for IDA Freeware 8.4 only), but they only work together with my other plugin and also Lumina server must use updated certificate as explained here https://github.com/naim94a/lumen/issues/124#issuecomment-1998793313.

**Comment by vikke1234** [comment]
I was not able to get this to work at first on my computer, socat was completely broken. Solved using socat from WSL2.

On an administrator powershell run: `netsh interface portproxy set v4tov4 listenport=1234 listenaddress=0.0.0.0 connectport=1234 connectaddress=$(wsl hostname -I)`

then on a wsl prompt run `socat -s -dd tcp4-listen:1234,fork,reuseaddr openssl:lumen.abda.nl:1235,verify=0,cafile=hexrays.crt`

**Comment by arialpew** [comment]
> Also you can try with this build of socat, i've compiled it myself and tested connection using it and it worked fine for me. It is different from other socat builds that you can find because it is configured and compiled with **--enable-openssl** option (you can check what compile options are used by running socat with -V switch).
> 
> [socat-1.8.0.0.zip](https://github.com/naim94a/lumen/files/13783206/socat-1.8.0.0.zip)
> 
> How to use: unpack all files from this achieve, start run.cmd file, in IDA options set lumina server to localhost and port 12345, user guest, password guest. LUMINA_TLS=false environment variable is required obviously.
> 
> To make sure you are starting IDA with LUMINA_TLS=false, you can create bat/cmd file in your IDA folder with following content:
> 
> ```
> @echo off
> set LUMINA_TLS=false
> set LUMINA_PRIMARY=guest:guest@localhost:12345
> set LUMINA_PRIMARY_TLS=false
> set LUMINA_SECONDARY=guest:guest@localhost:12345
> set LUMINA_SECONDARY_TLS=false
> ida64.exe
> ```
> 
> And use this batch file to start IDA instance.

Just want to say thanks you, you are a hero.

For anyone who are reading this : make sure your port 1234 is not ALREADY in-use otherwise you'll waste hours.

**Comment by greenozon** [comment]
@tomrus88   hi
do you think the old 8.x way will work on 9 beta?

**Comment by tomrus88** [comment]
> @tomrus88 hi do you think the old 8.x way will work on 9 beta?

Why not?
