### ISSUE TITLE
Lumina metadata history not working

### ISSUE THREAD

**Issue by tomrus88** [naim94a/lumen#122]
**Describe the bug**
Following error in IDA output window appears
```
Failed to get func histories from secondary lumina server: lumen: error: invalid data.

Failed to get func histories from primary lumina server: lumen: error: invalid data.

Command "LuminaMetadataHistory" failed
```

**To Reproduce**
Open context menu inside some function and select option Lumina -> Metadata History

**Expected behavior**
New window should open which shows historical information about function, such as:
 - Revision (1,2,3,...)
 - Timestamp (date & time)
 - Name (function name)
 - Author
 - IDB path

There's also 2 empty bottom panes which probably should show something as well...

**Server (please complete the following information):**
- Public server at lumen.abda.nl

**Client (please complete the following information):**
 - OS: Windows 11
 - Architecture: x86_64
 - IDA Version: 8.3

**Additional context**
- N/A

**Comment by tomrus88** [comment]
So far I see official server has following functionality:
```
0xA RPC_OK
0xB RPC_FAIL
0xC RPC_NOTIFY
0xD HELO
0xE PULL_MD
0xF PULL_MD_RESULT
0x10 PUSH_MD
0x11 PUSH_MD_RESULT
0x12 GET_POP
0x13 GET_POP_RESULT
0x14 LIST_PEERS
0x15 LIST_PEERS_RESULT
0x16 KILL_SESSIONS
0x17 KILL_SESSIONS_RESULT
0x18 DEL_HISTORY
0x19 DEL_HISTORY_RESULT
0x1A SHOW_HISTORY
0x1B SHOW_HISTORY_RESULT
0x1C DUMP_MD
0x1D DUMP_MD_RESULT
0x1E CLEAN_DB
0x1F DEBUGCTL
0x20 DECOMPILE
0x21 DECOMPILE_RESULT
0x22 PUSH_TLM
0x23 SHOW_TLM_SESSIONS
0x24 SHOW_TLM_SESSIONS_RESULT
0x25 SHOW_PUSHES
0x26 SHOW_PUSHES_RESULT
0x27 USER_OPERATION
0x28 SHOW_USERS
0x29 SHOW_USERS_RESULT
0x2A SET_PASSWORD
0x2B GET_LUMINA_INFO
0x2C GET_LUMINA_INFO_RESULT
0x2D GET_LUMINA_STATS
0x2E GET_LUMINA_STATS_RESULT
0x2F GET_FUNC_HISTORIES
0x30 GET_FUNC_HISTORIES_RESULT
0x31 HELO_RESULT
```

**Comment by naim94a** [comment]
merged to master :)

**Comment by tomrus88** [comment]
Nice! Thank you :)
