### ISSUE TITLE
Function names are garbled

### ISSUE THREAD

**Issue by WoxWik** [naim94a/lumen#123]
**Describe the bug**
Function names look garbled, or are using some strange format. What is the likely cause of this?

99% of my functions imported look like this no matter the library they are from.

**To Reproduce**
Lumina -> View All

**Expected behavior**
`Clear function names like TiXmlDeclaration instead of ??0TiXmlDeclaration@@QAE@PBD00@Z`

**Server (please complete the following information):**
lumen.abda.nl

**Client (please complete the following information):**
windows 11, 64bit, 8.3

**Comment by tomrus88** [comment]
That's called [Name mangling](https://en.wikipedia.org/wiki/Name_mangling) and likely intended.

**Comment by WoxWik** [comment]
That makes sense, thanks
