### ISSUE TITLE
"no peer certificate" bug

### ISSUE THREAD

**Issue by paidtoomuch** [naim94a/lumen#125]
**Environment:** Using IDA version 8.3 on a Windows system.

**Setup:** Installed and configured socat and openssl for Windows. Successfully created the 'hexrays.crt' file in the IDA 8.3 installation directory using openssl.

**Issue:** Encountering an SSL handshake failure error when attempting to connect to Lumina via socat server in powershell.

**Steps to Reproduce:**
1. Executed the command to start a socat server: `socat -s -dd tcp4-listen:1234,fork,reuseaddr openssl:lumen.abda.nl:1235,cafile=hexrays.crt`.
2. Ran a .bat file with the command set LUMINA_TLS=false to disable TLS for Lumina and then started ida64.exe through cmd using the bat file.
3. In IDA, navigated to the Lumina tab under options, entered "localhost" as the server, "1234" for the port, and used "guest" for both username and password.

**Error Observed:**
On applying these settings, an error was generated in the socat server running in PowerShell, indicating a problem with SSL handshake and certificate:
`2023/12/27 03:41:57 socat[2296] E SSL_connect(): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`
`2023/12/27 03:41:57 socat[2296] E no peer certificate`
`2023/12/27 03:41:57 socat[33544] W waitpid(): child 2296 exited with status 255`

**Comment by tomrus88** [comment]
Already been discussed before https://github.com/naim94a/lumen/issues/117
