### ISSUE TITLE
HelloResult implementation is incomplete

### ISSUE THREAD

**Issue by tomrus88** [naim94a/lumen#146]
**Describe the bug**
HelloResult response is not fully implemented
Related https://github.com/naim94a/lumen/discussions/144

**To Reproduce**
Some features are not enabled in IDA when using lumen server, such as Delete metadata

**Expected behavior**
Server should respond correctly with all needed information

**Server (please complete the following information):**
 - OS: whatever lumen.abda.nl uses
 - Architecture: whatever lumen.abda.nl uses

**Client (please complete the following information):**
 - OS: Windows 11
 - Architecture: x86_64
 - IDA Version: 8.3

**Additional context**
Correct structure of HelloResult is as following:
```
struct license_info_t
{
    qstring id; // license id
    qstring name; // license name?
    qstring email;
};

// lumina_user_t structure also used in some other unimplemented packets, such as:
// GET_LUMINA_STATS_RESULT
// SHOW_USERS_RESULT
// USER_OPERATION
// SHOW_PUSHES_RESULT
struct lumina_user_t
{
    license_info_t license_info;
    qstring name; // login name?
    uint32_t karma; // whatever that means lol
    uint64_t last_active; // unix time?
    uint32_t features; // flags: 0x2 appears to be can_delete_metadata, 0x1 likely is_admin, official lumina server sends 0x3 for admin accounts and 0x2 for regular accounts here
};

struct helo_result_t
{
    lumina_user_t user;
};
```

**Comment by tomrus88** [comment]
You got order of string fields mixed up, but other than that it should now work I guess.

**Comment by naim94a** [comment]
thanks! fixed
