### ISSUE TITLE
"Refresh" in Lumina window seems not working.

### ISSUE THREAD

**Issue by ChinaNuke** [naim94a/lumen#148]
**Describe the bug**
I can view all uploaded metadata via the "Lumina" -> "View all" entry. But the "Refresh" entry in the right-click menu in that window seems not working. When I push a function to lumen server, and then click the "Refresh" in the right-click menu in already opened lumina window, the newly pushed function does not appear. But if i close the lumina window, and repoen with "Lumina" -> "View all", the new function appears. So is the refresh function not implemented?

**To Reproduce**
Open the lumina window in IDA Pro with "Lumina" -> "View all", and keep it open. Push a new function with either in the right-click menu in IDA-View or in "Lumina" -> "Push function XXX". And then click "Refresh" in the right-click menu in the Lumina window.

**Expected behavior**
The newly pushed function appears in the lumina window.

**Server (please complete the following information):**
 - OS: ArchLinux
 - Architecture: x86_64

**Client (please complete the following information):**
 - OS: ArchLinux
 - Architecture: x86_64
 - IDA Version: 8.4

**Comment by tomrus88** [comment]
It doesn't work with official Lumina server too, so report it to IDA developers instead.

**Comment by ChinaNuke** [comment]
Got it, thank you!
