### ISSUE TITLE
Did I get banned from this Lumen Server?

### ISSUE THREAD

**Issue by fatrolls** [naim94a/lumen#16]
I get this when I Push to your Lumen DB
![banned](https://i.imgur.com/IxhTtKZ.png)

But pulling from Lumen DB is no problem I get all the results..

I pushed alot of function prototypes to Lumen about 30,000 I have a bunch of pdb's for many MMO game servers I am trying to make it a complete lumen server.

Edit: now I can't even Pull from lumen server.

![banned](https://i.imgur.com/jV0XUMR.png)

If I go on VPN connection it starts working for pulling but still doesn't push

![banned](https://i.imgur.com/UEXRWeA.png)

Now it's working again thanks
![working](https://i.imgur.com/N8i10MZ.png)

Some of my submissions :D
![submissions](https://i.imgur.com/RTVb0ek.png)
![submissions2](https://i.imgur.com/ifRRmgl.png)
![submissions3](https://i.imgur.com/8fOxkNs.png)
Wow 7 MB submission.. also failed
![failed 7MB](https://i.imgur.com/AEBBER8.png)
![submissions4](https://i.imgur.com/GMGE0pi.png)

**Comment by naim94a** [comment]
You didn't get banned.
My database server just ran out of space! Added more storage... 
Thanks for your contribution :)

**Comment by fatrolls** [comment]
Thanks how big of a database are we talking about? just curious :P

worked now!
![works now](https://i.imgur.com/MpmzKwb.png)

**Comment by naim94a** [comment]
It was 15gb.
I should work on optimizing the way data is stored to reduce storage...

**Comment by fatrolls** [comment]
That's not that bad to be honest
ya or just compress the database on the fly.

Thanks again back to contributing now data now :p
