### ISSUE TITLE
Database Availability

### ISSUE THREAD

**Issue by NakaTheShifu** [naim94a/lumen#31]
Hello,

I'm part of a malware research and analysis team that has taken steps to perform our research and analysis in an airgapped environment, with our own simulated "internet" and the likes of it. We came across lumen as an offline alternative to _lumina_, and we are fairly interested to see if it's possible for the database to be made open source and downloadable? 

As means of re-contribution, we are also open to any suggestions of how we can obtain the changes we make in our own environment and push back to the community database?

**Comment by naim94a** [comment]
I’m not planning to release the database.
