### ISSUE TITLE
ERROR lumen > push failed, db: db error: ERROR: value too long for type character varying(1000)

### ISSUE THREAD

**Issue by ThisIsMyAltAccount** [naim94a/lumen#4]
**Describe the bug**
Pushing metadata for entire ```mshtml.dll``` from Windows 7 SP1  fails.

https://www.dropbox.com/s/wg5eufi9odmz3i3/mshtml.7z?dl=0

**To Reproduce**
1, Setup Windows Symbol path.
2, Open ```mshtml.dll```.
3, Let it download the symbol file and analyze. 
4, Push to Lumina server when finished analyzing.

```
lumina: lumen.abda.nl: db error; please try again later.
Command "LuminaPushAllMds" failed
```

**Expected behavior**
Push metadata without failing.

**Server (please complete the following information):**
 - OS: Debian 10.
 - Architecture:  x86_64
 - Postgresql (11+200+deb10u4)
 - Rust: 1.48.0 (7eac88abb 2020-11-16)

**Client (please complete the following information):**
 - OS: Windows 7
 - Architecture: x86_64
 - IDA Version: 7.3sp3

```
LUMINA_HOST = "192.168.1.100";
LUMINA_PORT = 1234
LUMINA_TLS = NO
LUMINA_MIN_FUNC_SIZE = 32
```

**Additional context**

(Not related, but you have a typo in the domain name, src/main.rs line 84.)

**Comment by naim94a** [comment]
Thanks for the report!
I will apply a patch to schema.sql later... 
To update the existing table, execute: (this should resolve the issue)
```sql
ALTER TABLE funcs ALTER COLUMN name SET DATA TYPE TEXT;
```
And then restart the server (cached prepared transactions may cause problems on a modified table).

**Comment by ThisIsMyAltAccount** [comment]
Success! Thanks.
```
mshtml.dll

57737 new out of 57738 (0.999983 ratio)
*** Thank you for your contribution! ***
```

```
wmp.dll
21877 new out of 21893 (0.999269 ratio)
*** Thank you for your contribution! ***
```
