### ISSUE TITLE
IDA 8.1 Auth Support

### ISSUE THREAD

**Issue by LloydLabs** [naim94a/lumen#41]
**Describe the bug**
IDA 8.1 added the option to use a private Lumina server in the UI, it however requires authentication when connecting to it, which unfortunately Lumen doesn't currently support. This is likely so Hex-Rays can shift to using their own private server in which they distribute to their users.

The environment variable, `LUMINA_HOST` does not work either without authentication being provided.

**To Reproduce**
Options -> Lumina -> Private Lumina Server

**Expected behavior**
Lumen server being able to auth

**Server (please complete the following information):**
 - OS: N/A
 - Architecture: N/A

**Client (please complete the following information):**
 - OS: Windows 10
 - Architecture: x86_64
 - IDA Version: 8.1

**Additional context**
https://hex-rays.com/products/ida/news/8_1/

**Comment by naim94a** [comment]
I would like to add support, but that would be difficult since I do not have IDA8.x yet :-(
