### ISSUE TITLE
IDA Pro 8.1 issue on connect

### ISSUE THREAD

**Issue by bkerler** [naim94a/lumen#43]
**Describe the bug**
Connection to the lumen server isn't possible with IDA Pro 8.1 for a unknown reason.

**To Reproduce**
Trying to connect to the lumen server, it fails with
` 2022-10-18T06:38:53.057Z INFO  lumen > listening on 0.0.0.0:1234 secure=false
 2022-10-18T06:38:59.754Z WARN  lumen > err: IOError(Custom { kind: InvalidData, error: "request length exceeded maximum limit" })
`

**Expected behavior**
Lumen connection does work.

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: x86_64

**Client (please complete the following information):**
 - OS: Ubuntu 22.04
 - Architecture: x86_64
 - IDA Version: 8.1

**Additional context**
More details for setting up a ida 8.1 server in the readme.md (such as: "Only use guest as username/password") might help.
IDA Pro 8.1 seems to ignore LUMEN_TLS = NO, giving a warning about being an invalid configuration parameter. A custom hexrays.crt isn't accepted.

**Comment by naim94a** [comment]
I should add this to the README… 
In IDA8.1+ these settings (LUMINA_HOST, LUMINA_PORT, LUMINA_TLA, LUMINA_USER, LUMINA_PASS) can either be set in the registry, or via environment variables (all except LUMINA_TLS) can be set in the UI.
The TLS certificate is only hardcoded now and IDA doesn’t seem to have a way to override it, so a plugin (wip) is required to override the certificate. I didn’t get the time to work on that part yet.

**Comment by bkerler** [comment]
Ok, can you specify how you made it work with 8.1 and with tls being off ? Setting these variables in the ida.cfg or idauser.cfg doesn't seem to work and neither trying to set it in the gui seem to work. I'd be glad for any hint ;)

**Comment by naim94a** [comment]
Either in the registry or via environment variables…

**Comment by bkerler** [comment]
Took some time to figure out (registry doesn't work under Linux), so I decided to add instructions to the readme:
https://github.com/naim94a/lumen/pull/47

All working fine now. Thanks !
