### ISSUE TITLE
InitializeSecurityContext error on IDA 7.6

### ISSUE THREAD

**Issue by anzz1** [naim94a/lumen#44]
**Describe the bug**
The public server fails with message:
```
lumina: InitializeSecurityContext[2]: The message received was unexpected or badly formatted.
Command "LuminaViewAllMds" failed
```

I suspect that this is a problem with SSL misconfiguration on the server side, specifically using a wrong TLS cipher (or in case multiple ciphers are configured, missing support) for the one used client-side in IDA 7.6, but I'm not certain.

This is the configuration:
```
LUMINA_HOST = "lumen.abda.nl";
LUMINA_PORT = 1235
LUMINA_TLS = YES
```

With `LUMINA_TLS = NO` , connection isn't established at all ("connection reset by peer")

**To Reproduce**
Lumina -> View All Metadata

**Server (please complete the following information):**
 - lumen.abda.nl:1235 (public server)

**Client (please complete the following information):**
 - OS: Windows 7 SP2
 - Architecture: x86_64
 - IDA Version: 7.6sp1

**Comment by naim94a** [comment]
Just to be sure, did you use copy the [hexrays.crt](https://abda.nl/lumen/hexrays.crt) to IDA's installation directory?

**Comment by anzz1** [comment]
@naim94a Yes

**Comment by anzz1** [comment]
For more context, in the system Event Viewer, "Windows Logs -> System", a Schannel error with eventid 36887 can be found:
"The following fatal alert was received: 40."

and that error code corresponds to:

`40 = SSL3_ALERT_HANDSHAKE_FAILURE`

**Comment by naim94a** [comment]
Thanks for sharing the details! Please confirm that this works now?

**Comment by anzz1** [comment]
It doesn't fail to the handshake anymore, and goes through the first "Calculating patterns ..." phase, but then gets indefinitely stuck on the 2nd phase:
```
Retrieving metadata
(sent 0 bytes out of 1723843)
```

**Comment by naim94a** [comment]
It means that the server is waiting for the query to return from the database (I don't know why it's too slow). Either wait a bit more until it resolves the query or select specific functions should speed up the query.
One of the issues with the protocol design is that the server must know which results exist and which don't before sending a reply, which causes a bottleneck for chunking the query on the server side.

**Comment by anzz1** [comment]
Ahh, I see. I tried with another, smaller, file, and it worked fine !

As the one I tried first was a 700MB database from a 80MB memory dump of a 60MB executable with 100k+ functions, so that must've been it. For large databases it seems to get stuck forever.
