### ISSUE TITLE
error encoding message to server

### ISSUE THREAD

**Issue by wbaby** [naim94a/lumen#67]
IDA 8.2
Lumina -> push all metadata

ERROR lumen > push failed, db: error encoding message to server: value too large to transmit

**Comment by naim94a** [comment]
Could you please confirm that #68 resolves this?

**Comment by wbaby** [comment]
> 

Compiled and tested with no issues.

There is another problem, IDA8.2 has no place to set LUMINA_MIN_FUNC_SIZE, and the environment variable test has no effect.

**Comment by naim94a** [comment]
If I’m not mistaken, Hex-Rays removed all LUMINA_* variables from the configuration in 8.0. Instead I could add a configuration on the server side to discard functions under a specified length…
