### ISSUE TITLE
Stuck with Retrieving metadata

### ISSUE THREAD

**Issue by Pinguu-dev** [naim94a/lumen#73]
Does not work for me anymore, after pulling he stuck with 
"Retrieving metadata, 0 bytes out of 5941145"

After i wait ~ 5 MIn:

recv_data: recv: An existing connection was forcibly closed by the remote host.
lumina: connection closed (recv: An existing connection was forcibly closed by the remote host.). Trying to reconnect...
recv_data: recv: An existing connection was forcibly closed by the remote host.
lumina: No response
Command "LuminaPullAllMds" failed

**Comment by naim94a** [comment]
Pull queries are currently limited to 5 minutes… 
Of course the limit could be changed the question is how much time would be fair limit?

**Comment by Pinguu-dev** [comment]
10 ~ 15?
