### ISSUE TITLE
lumina: Schannel does not support the requested security attributes 

### ISSUE THREAD

**Issue by H5GG** [naim94a/lumen#88]
<img width="616" alt="image" src="https://user-images.githubusercontent.com/74475614/235738461-0de6a913-d671-4046-a40a-8e2796c6430a.png">
<img width="324" alt="image" src="https://user-images.githubusercontent.com/74475614/235738483-7199780e-f4d1-4ac6-9531-17b7bbf3b020.png">

ida7.6 windows, cert  updated[https://abda.nl/lumen/hexrays.crt]

**Comment by naim94a** [comment]
1. The error with Schannel is dependent on the OS - I'm not sure why Schannel wouldn't support any of the attributes on lumen.abda.nl's certificate. There isn't much that I can do about that at the moment.
2. Assuming the second comment is connected to lumen.abda.nl - non TLS connections would be immediately dropped... You might be able to workaround using socat:

  - Using `socat` to encapsulate TLS:
  ```cmd.exe
  socat -s -dd tcp4-listen:1234,fork,reuseaddr openssl:lumen.abda.nl:1235,cafile=hexrays.crt
  ```

  - Configuring IDA to use the local server:
  ```c
  LUMINA_TLS = NO
  LUNINA_HOST = "localhost";
  LUMINA_PORT = 1234
  ```
